name: query-exporter
version: git
summary: Export Prometheus metrics from SQL queries
description: |
  query-exporter is a Prometheus exporter which allows collecting metrics from
  database queries, at specified time intervals or when a request to the
  metrics endpoint is performed.

  Each query can be run on multiple databases, and update multiple metrics.

  The snap provides both the `query-exporter` command and a deamon instance of
  the command, managed via a Systemd service.
  To run the latter:

    - create or edit `/var/snap/query-exporter/current/config.yaml` with the
      configuration
    - run `sudo snap restart query-exporter`

  Currently supported databases are:

    - MySQL
    - PostgreSQL
    - SQLite

license: GPL-3.0+
confinement: strict
grade: stable
base: core18

apps:
  daemon:
    command: bin/query-exporter -H 0.0.0.0 $SNAP_DATA/config.yaml
    daemon: simple
    plugs:
      - network-bind
      - network
  query-exporter:
    command: bin/query-exporter
    plugs:
      - home
      - network-bind
      - network

parts:
  query-exporter:
    plugin: python
    source: .
    source-type: git
    python-packages:
      - mysql
      - psycopg2
    build-packages:
      - libmysqlclient-dev
      - libpq-dev
    stage-packages:
      - libmysqlclient20
      - libpq5
    filesets:
      bins:
        - bin/query-exporter
        - usr/bin/python3
        - usr/bin/python3.6
      libs:
        - lib
        - usr/lib
        - -usr/lib/python3.7
    prime:
      - $bins
      - etc/python3.6
      - $libs
